/**
 * Evolution Auto Sale — digital business card assets
 *
 * Writes the two static files behind /card:
 *   - public/evolution-auto-sale.vcf   "Save contact" download
 *   - components/card/qr.ts            the card URL as SVG path data
 *
 * Both are built from config/site.ts, so re-run this after changing the
 * business details there:
 *
 *   node scripts/build-card.mjs
 *
 * The contact carries only confirmed facts — name, city and state, website,
 * Instagram and the booking profile. No phone number, email or street address,
 * because none has been confirmed (see CLAUDE.md).
 */
import { readFile, writeFile } from "node:fs/promises";
import QRCode from "qrcode";
import sharp from "sharp";

/* config/site.ts is TypeScript, so read the few string values it holds with a
   pattern rather than importing it. */
const config = await readFile("config/site.ts", "utf8");
const field = (name) => {
  const match = config.match(new RegExp(`${name}:\\s*"([^"]+)"`));
  if (!match) throw new Error(`config/site.ts: missing ${name}`);
  return match[1];
};

const site = {
  businessName: field("businessName"),
  city: field("city"),
  region: field("region"),
  instagramUrl: field("instagramUrl"),
  instagramHandle: field("instagramHandle"),
  bookingProfileUrl: field("bookingProfileUrl"),
  siteUrl: field("siteUrl"),
  fleetCount: field("fleetCount"),
};

const cardUrl = `${site.siteUrl}/card`;

/* ---------- vCard 3.0 ---------- */

/* vCard text values escape backslash, comma and semicolon; lines fold at 75
   octets with a leading space on each continuation. */
const escape = (value) => value.replace(/\\/g, "\\\\").replace(/,/g, "\\,").replace(/;/g, "\\;");
const fold = (line) => {
  const out = [];
  for (let i = 0; i < line.length; i += 74) out.push((i ? " " : "") + line.slice(i, i + 74));
  return out.join("\r\n");
};

/* The circular brand mark as the contact photo, small enough that phones
   accept it without complaint. */
const photo = (
  await sharp("public/images/brand/mark.webp").resize(150, 150).jpeg({ quality: 82 }).toBuffer()
).toString("base64");

const vcard = [
  "BEGIN:VCARD",
  "VERSION:3.0",
  `FN:${escape(site.businessName)}`,
  /* An organisation card: no person's name, and Apple Contacts files it under
     the company rather than an empty contact. */
  `N:${escape(site.businessName)};;;;`,
  "X-ABShowAs:COMPANY",
  `ORG:${escape(site.businessName)}`,
  `TITLE:${escape("Specialty Vehicle Rentals")}`,
  `ADR;TYPE=WORK:;;;${escape(site.city)};${site.region};;USA`,
  `URL:${site.siteUrl}`,
  `item1.URL:${site.instagramUrl}`,
  `item1.X-ABLabel:Instagram ${escape(site.instagramHandle)}`,
  `item2.URL:${site.bookingProfileUrl}`,
  `item2.X-ABLabel:Live availability`,
  `NOTE:${escape(`${site.fleetCount} vehicle specialty rental fleet in ${site.city}, ${site.region}.`)}`,
  `PHOTO;ENCODING=b;TYPE=JPEG:${photo}`,
  "END:VCARD",
]
  .map(fold)
  .join("\r\n");

await writeFile("public/evolution-auto-sale.vcf", vcard + "\r\n");
console.log(`public/evolution-auto-sale.vcf   ${Math.round(vcard.length / 1024)}KB`);

/* ---------- QR code ---------- */

/* Emitted as path data plus the module count rather than a finished SVG, so
   the component can colour it from the design tokens like everything else. */
const svg = await QRCode.toString(cardUrl, { type: "svg", errorCorrectionLevel: "M", margin: 0 });
const viewBox = svg.match(/viewBox="0 0 (\d+) (\d+)"/);
const paths = [...svg.matchAll(/<path[^>]*stroke="#000000"[^>]*d="([^"]+)"/g)].map((m) => m[1]);
if (!viewBox || paths.length !== 1) throw new Error("Unexpected qrcode SVG output");

await writeFile(
  "components/card/qr.ts",
  `/* Generated by scripts/build-card.mjs — do not edit by hand. */\n` +
    `export const cardUrl = ${JSON.stringify(cardUrl)};\n` +
    `export const qrSize = ${viewBox[1]};\n` +
    `export const qrPath = ${JSON.stringify(paths[0])};\n`,
);
console.log(`components/card/qr.ts           ${viewBox[1]} modules → ${cardUrl}`);
