import { existsSync } from "node:fs";
import { join } from "node:path";
import type { Metadata } from "next";
import Image from "next/image";
import { ArrowUpRight, Download, Globe, Wallet } from "lucide-react";
import { bookingHref, siteConfig } from "@/config/site";
import { BrandMark } from "@/components/ui/BrandMark";
import { InstagramGlyph } from "@/components/ui/InstagramGlyph";
import { Wordmark } from "@/components/ui/Wordmark";
import { ShareButton } from "@/components/card/ShareButton";
import { cardUrl, qrPath, qrSize } from "@/components/card/qr";

export const metadata: Metadata = {
  title: "Digital Card",
  description: `${siteConfig.businessName}: specialty vehicle rentals in ${siteConfig.location}.`,
  alternates: { canonical: "/card" },
  /* A pocket version of the home page, not a page to rank on its own. */
  robots: { index: false, follow: true },
};

/* Only offered once scripts/build-wallet-pass.mjs has produced a signed pass,
   which needs the owner's Apple Developer certificate. Checked at build time,
   so the static export never ships a button that leads nowhere. */
const walletPass = "/evolution-auto-sale.pkpass";
const hasWalletPass = existsSync(join(process.cwd(), "public", walletPass));

const facts = [
  { value: siteConfig.fleetCount, label: "Vehicles" },
  { value: siteConfig.city, label: siteConfig.region },
  { value: "Specialty", label: "Rentals" },
];

const links = [
  {
    href: siteConfig.instagramUrl,
    icon: <InstagramGlyph className="size-[18px]" />,
    label: "Instagram",
    detail: siteConfig.instagramHandle,
    external: true,
  },
  {
    href: "/",
    icon: <Globe className="size-[18px]" strokeWidth={1.5} aria-hidden="true" />,
    label: "Website",
    detail: siteConfig.siteUrl.replace(/^https?:\/\//, ""),
    external: false,
  },
];

/**
 * Digital business card. Built to be opened on a phone and handed across a
 * counter: one screen, everything a tap away, and a QR code that opens this
 * same card on the other person's phone. Contact details are limited to the
 * confirmed facts in CLAUDE.md, so there is no phone number or email.
 *
 * The QR path data and the .vcf download are generated by
 * scripts/build-card.mjs from config/site.ts.
 */
export default function CardPage() {
  return (
    <main className="flex min-h-[100svh] items-center justify-center px-4 py-10 sm:py-16">
      <article
        aria-labelledby="card-name"
        className="w-full max-w-[420px] overflow-hidden rounded-[28px] border border-line bg-elevated shadow-2xl shadow-black/70"
      >
        {/* The studio car, fading into the card so the mark can sit over it. */}
        <div className="relative aspect-[4/3]">
          <Image
            src="/images/brand/studio.webp"
            alt="The white Evolution Evo X on a dark studio seamless"
            fill
            priority
            sizes="420px"
            className="studio-image object-cover"
          />
          <div aria-hidden="true" className="absolute inset-0 bg-gradient-to-t from-elevated via-elevated/20 to-transparent" />
        </div>

        <div className="relative -mt-12 px-7 pb-8">
          <BrandMark size={64} className="ring-2 ring-elevated" />

          <h1 id="card-name" className="mt-5">
            <Wordmark />
            <span className="sr-only"> — {siteConfig.businessName}</span>
          </h1>
          <p className="eyebrow mt-3 flex items-center gap-3">
            <span aria-hidden="true" className="block h-px w-6 bg-accent" />
            {siteConfig.location}
          </p>

          <ul className="mt-7 grid grid-cols-[0.8fr_1.15fr_1.05fr] border-y border-line">
            {facts.map((fact, index) => (
              <li key={fact.label} className={`min-w-0 py-4 ${index ? "border-l border-line pl-3" : ""}`}>
                <span className="font-display block text-[0.8125rem] font-medium uppercase leading-none tracking-[0.01em] min-[400px]:text-[0.9375rem]">
                  {fact.value}
                </span>
                <span className="label-micro mt-2 block text-muted">{fact.label}</span>
              </li>
            ))}
          </ul>

          <a
            href={bookingHref}
            target="_blank"
            rel="noopener noreferrer"
            className="group mt-7 flex min-h-14 items-center justify-center gap-2 rounded-full bg-accent px-6 text-[0.8125rem] font-medium uppercase tracking-[0.08em] text-bg transition duration-300 hover:bg-ink"
          >
            View Live Availability
            <ArrowUpRight className="size-4 transition-transform duration-300 group-hover:translate-x-0.5 group-hover:-translate-y-0.5" aria-hidden="true" />
          </a>

          <ul className="mt-5 divide-y divide-line border-y border-line">
            {links.map((link) => (
              <li key={link.label}>
                <a
                  href={link.href}
                  {...(link.external ? { target: "_blank", rel: "noopener noreferrer" } : {})}
                  className="group flex items-center gap-4 py-4 transition-colors duration-300 hover:text-accent"
                >
                  <span className="inline-flex size-10 shrink-0 items-center justify-center rounded-full border border-line text-muted transition-colors duration-300 group-hover:border-accent group-hover:text-accent">
                    {link.icon}
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="block text-[0.9375rem] font-medium">{link.label}</span>
                    <span className="block truncate text-sm text-muted">{link.detail}</span>
                  </span>
                  <ArrowUpRight className="size-4 text-muted transition-colors duration-300 group-hover:text-accent" aria-hidden="true" />
                </a>
              </li>
            ))}
          </ul>

          <div className="mt-6 flex flex-col gap-3 min-[400px]:flex-row">
            <a
              href="/evolution-auto-sale.vcf"
              download="Evolution Auto Sale.vcf"
              className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 whitespace-nowrap rounded-full bg-ink px-4 text-[0.75rem] font-medium uppercase tracking-[0.06em] text-bg transition duration-300 hover:bg-accent"
            >
              <Download className="size-4" aria-hidden="true" />
              Save contact
            </a>
            <ShareButton
              url={cardUrl}
              title={siteConfig.businessName}
              text={`${siteConfig.businessName}: specialty vehicle rentals in ${siteConfig.location}.`}
            />
          </div>

          {hasWalletPass ? (
            <a
              href={walletPass}
              className="mt-3 flex min-h-12 items-center justify-center gap-2 rounded-full border border-line-strong px-4 text-[0.75rem] font-medium uppercase tracking-[0.06em] text-ink transition duration-300 hover:border-accent hover:text-accent"
            >
              <Wallet className="size-4" aria-hidden="true" />
              Add to Apple Wallet
            </a>
          ) : null}

          {/* Dark modules on a light tile: phone cameras read that far more
              reliably than the inverse. */}
          <div className="mt-8 flex items-center gap-5 rounded-2xl border border-line bg-bg/60 p-4">
            <svg
              viewBox={`0 0 ${qrSize} ${qrSize}`}
              role="img"
              aria-label={`QR code opening ${cardUrl}`}
              shapeRendering="crispEdges"
              className="size-24 shrink-0 rounded-lg bg-ink p-2"
            >
              <path d={qrPath} className="stroke-bg" fill="none" />
            </svg>
            <div>
              <p className="label-micro text-accent">Scan to save</p>
              <p className="mt-2 text-sm leading-relaxed text-muted">
                Point a phone camera here to open this card.
              </p>
            </div>
          </div>

          <p className="mt-7 text-center text-xs leading-relaxed text-muted">
            Bookings, pricing and availability are handled on the external booking platform.
            <br />
            <a href="/legal" className="mt-2 inline-block underline-offset-4 transition-colors duration-300 hover:text-ink hover:underline">
              Privacy &amp; Legal
            </a>
          </p>
        </div>
      </article>
    </main>
  );
}
